FROM ruby:3.2

# Node, Yarn, PostgreSQLクライアント、Heroku CLIなど開発で必要なもの
RUN apt-get update -qq && apt-get install -y \
  nodejs \
  yarn \
  postgresql-client && \
  curl https://cli-assets.heroku.com/install.sh | sh

WORKDIR /app

# Gemfileを先にコピーしてbundle install
COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install

RUN apt-get update && apt-get install -y watchman

# ホスト側コードをボリュームマウントする想定なのでCOPY . . は不要

EXPOSE 3000

# 起動コマンドはdocker-compose.yml側で指定する